//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_novaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расширение.
    /// </summary>
    // *** Start programmer edit section *** (Расширение CustomAttributes)

    // *** End programmer edit section *** (Расширение CustomAttributes)
    public enum Расширение
    {
        
        // *** Start programmer edit section *** (Расширение.pdf CustomAttributes)

        // *** End programmer edit section *** (Расширение.pdf CustomAttributes)
        [Caption("pdf")]
        pdf,
        
        // *** Start programmer edit section *** (Расширение.step CustomAttributes)

        // *** End programmer edit section *** (Расширение.step CustomAttributes)
        [Caption("step")]
        step,
        
        // *** Start programmer edit section *** (Расширение.obj CustomAttributes)

        // *** End programmer edit section *** (Расширение.obj CustomAttributes)
        [Caption("obj")]
        obj,
        
        // *** Start programmer edit section *** (Расширение.dxf CustomAttributes)

        // *** End programmer edit section *** (Расширение.dxf CustomAttributes)
        [Caption("dxf")]
        dxf,
        
        // *** Start programmer edit section *** (Расширение.xml CustomAttributes)

        // *** End programmer edit section *** (Расширение.xml CustomAttributes)
        [Caption("xml")]
        xml,
    }
}
