//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_novaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тех карты.
    /// </summary>
    // *** Start programmer edit section *** (ТехКарты CustomAttributes)

    // *** End programmer edit section *** (ТехКарты CustomAttributes)
    [AutoAltered()]
    [Caption("Тех карты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТехКартыE", new string[] {
            "НомерКарты as \'Номер карты\'",
            "Дата as \'Дата\'",
            "Чертежи as \'Чертежи\'",
            "Чертежи.НаименЧертеж as \'Наименование чертежа\'"}, Hidden=new string[] {
            "Чертежи.НаименЧертеж"})]
    [AssociatedDetailViewAttribute("ТехКартыE", "ТЧТехКарты", "ТЧТехКартыE", true, "", "Этапы", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ТехКартыE", "Чертежи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаименЧертеж")]
    [View("ТехКартыL", new string[] {
            "НомерКарты as \'Номер карты\'",
            "Дата as \'Дата\'",
            "Чертежи.НаименЧертеж as \'Наименование чертеж\'"})]
    public class ТехКарты : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКарты;
        
        private System.DateTime fДата;
        
        private IIS.Generaciya_novaya.Чертежи fЧертежи;
        
        private IIS.Generaciya_novaya.DetailArrayOfТЧТехКарты fТЧТехКарты;
        
        // *** Start programmer edit section *** (ТехКарты CustomMembers)

        // *** End programmer edit section *** (ТехКарты CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарты.Дата CustomAttributes)

        // *** End programmer edit section *** (ТехКарты.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарты.Дата Get start)

                // *** End programmer edit section *** (ТехКарты.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ТехКарты.Дата Get end)

                // *** End programmer edit section *** (ТехКарты.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарты.Дата Set start)

                // *** End programmer edit section *** (ТехКарты.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ТехКарты.Дата Set end)

                // *** End programmer edit section *** (ТехКарты.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерКарты.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарты.НомерКарты CustomAttributes)

        // *** End programmer edit section *** (ТехКарты.НомерКарты CustomAttributes)
        public virtual int НомерКарты
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Get start)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Get start)
                int result = this.fНомерКарты;
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Get end)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Set start)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Set start)
                this.fНомерКарты = value;
                // *** Start programmer edit section *** (ТехКарты.НомерКарты Set end)

                // *** End programmer edit section *** (ТехКарты.НомерКарты Set end)
            }
        }
        
        /// <summary>
        /// Тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарты.Чертежи CustomAttributes)

        // *** End programmer edit section *** (ТехКарты.Чертежи CustomAttributes)
        [PropertyStorage(new string[] {
                "Чертежи"})]
        [NotNull()]
        public virtual IIS.Generaciya_novaya.Чертежи Чертежи
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарты.Чертежи Get start)

                // *** End programmer edit section *** (ТехКарты.Чертежи Get start)
                IIS.Generaciya_novaya.Чертежи result = this.fЧертежи;
                // *** Start programmer edit section *** (ТехКарты.Чертежи Get end)

                // *** End programmer edit section *** (ТехКарты.Чертежи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарты.Чертежи Set start)

                // *** End programmer edit section *** (ТехКарты.Чертежи Set start)
                this.fЧертежи = value;
                // *** Start programmer edit section *** (ТехКарты.Чертежи Set end)

                // *** End programmer edit section *** (ТехКарты.Чертежи Set end)
            }
        }
        
        /// <summary>
        /// Тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарты.ТЧТехКарты CustomAttributes)

        // *** End programmer edit section *** (ТехКарты.ТЧТехКарты CustomAttributes)
        public virtual IIS.Generaciya_novaya.DetailArrayOfТЧТехКарты ТЧТехКарты
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарты.ТЧТехКарты Get start)

                // *** End programmer edit section *** (ТехКарты.ТЧТехКарты Get start)
                if ((this.fТЧТехКарты == null))
                {
                    this.fТЧТехКарты = new IIS.Generaciya_novaya.DetailArrayOfТЧТехКарты(this);
                }
                IIS.Generaciya_novaya.DetailArrayOfТЧТехКарты result = this.fТЧТехКарты;
                // *** Start programmer edit section *** (ТехКарты.ТЧТехКарты Get end)

                // *** End programmer edit section *** (ТехКарты.ТЧТехКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарты.ТЧТехКарты Set start)

                // *** End programmer edit section *** (ТехКарты.ТЧТехКарты Set start)
                this.fТЧТехКарты = value;
                // *** Start programmer edit section *** (ТехКарты.ТЧТехКарты Set end)

                // *** End programmer edit section *** (ТехКарты.ТЧТехКарты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТехКартыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТехКартыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТехКартыE", typeof(IIS.Generaciya_novaya.ТехКарты));
                }
            }
            
            /// <summary>
            /// "ТехКартыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТехКартыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТехКартыL", typeof(IIS.Generaciya_novaya.ТехКарты));
                }
            }
        }
    }
}
