//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_novaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч чертежи.
    /// </summary>
    // *** Start programmer edit section *** (ТчЧертежи CustomAttributes)

    // *** End programmer edit section *** (ТчЧертежи CustomAttributes)
    [AutoAltered()]
    [Caption("Тч чертежи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчЧертежиE", new string[] {
            "Версия as \'Версия файла\'",
            "ИмяФайла as \'Имя файла\'",
            "Расширение as \'Расширение\'",
            "ДатаИзм as \'Дата изменения\'"})]
    public class ТчЧертежи : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмяФайла;
        
        private IIS.Generaciya_novaya.Расширение fРасширение;
        
        private System.DateTime fДатаИзм;
        
        private float fВерсия;
        
        private IIS.Generaciya_novaya.Чертежи fЧертежи;
        
        // *** Start programmer edit section *** (ТчЧертежи CustomMembers)

        // *** End programmer edit section *** (ТчЧертежи CustomMembers)

        
        /// <summary>
        /// Версия.
        /// </summary>
        // *** Start programmer edit section *** (ТчЧертежи.Версия CustomAttributes)

        // *** End programmer edit section *** (ТчЧертежи.Версия CustomAttributes)
        public virtual float Версия
        {
            get
            {
                // *** Start programmer edit section *** (ТчЧертежи.Версия Get start)

                // *** End programmer edit section *** (ТчЧертежи.Версия Get start)
                float result = this.fВерсия;
                // *** Start programmer edit section *** (ТчЧертежи.Версия Get end)

                // *** End programmer edit section *** (ТчЧертежи.Версия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЧертежи.Версия Set start)

                // *** End programmer edit section *** (ТчЧертежи.Версия Set start)
                this.fВерсия = value;
                // *** Start programmer edit section *** (ТчЧертежи.Версия Set end)

                // *** End programmer edit section *** (ТчЧертежи.Версия Set end)
            }
        }
        
        /// <summary>
        /// ДатаИзм.
        /// </summary>
        // *** Start programmer edit section *** (ТчЧертежи.ДатаИзм CustomAttributes)

        // *** End programmer edit section *** (ТчЧертежи.ДатаИзм CustomAttributes)
        public virtual System.DateTime ДатаИзм
        {
            get
            {
                // *** Start programmer edit section *** (ТчЧертежи.ДатаИзм Get start)

                // *** End programmer edit section *** (ТчЧертежи.ДатаИзм Get start)
                System.DateTime result = this.fДатаИзм;
                // *** Start programmer edit section *** (ТчЧертежи.ДатаИзм Get end)

                // *** End programmer edit section *** (ТчЧертежи.ДатаИзм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЧертежи.ДатаИзм Set start)

                // *** End programmer edit section *** (ТчЧертежи.ДатаИзм Set start)
                this.fДатаИзм = value;
                // *** Start programmer edit section *** (ТчЧертежи.ДатаИзм Set end)

                // *** End programmer edit section *** (ТчЧертежи.ДатаИзм Set end)
            }
        }
        
        /// <summary>
        /// ИмяФайла.
        /// </summary>
        // *** Start programmer edit section *** (ТчЧертежи.ИмяФайла CustomAttributes)

        // *** End programmer edit section *** (ТчЧертежи.ИмяФайла CustomAttributes)
        [StrLen(255)]
        public virtual string ИмяФайла
        {
            get
            {
                // *** Start programmer edit section *** (ТчЧертежи.ИмяФайла Get start)

                // *** End programmer edit section *** (ТчЧертежи.ИмяФайла Get start)
                string result = this.fИмяФайла;
                // *** Start programmer edit section *** (ТчЧертежи.ИмяФайла Get end)

                // *** End programmer edit section *** (ТчЧертежи.ИмяФайла Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЧертежи.ИмяФайла Set start)

                // *** End programmer edit section *** (ТчЧертежи.ИмяФайла Set start)
                this.fИмяФайла = value;
                // *** Start programmer edit section *** (ТчЧертежи.ИмяФайла Set end)

                // *** End programmer edit section *** (ТчЧертежи.ИмяФайла Set end)
            }
        }
        
        /// <summary>
        /// Расширение.
        /// </summary>
        // *** Start programmer edit section *** (ТчЧертежи.Расширение CustomAttributes)

        // *** End programmer edit section *** (ТчЧертежи.Расширение CustomAttributes)
        public virtual IIS.Generaciya_novaya.Расширение Расширение
        {
            get
            {
                // *** Start programmer edit section *** (ТчЧертежи.Расширение Get start)

                // *** End programmer edit section *** (ТчЧертежи.Расширение Get start)
                IIS.Generaciya_novaya.Расширение result = this.fРасширение;
                // *** Start programmer edit section *** (ТчЧертежи.Расширение Get end)

                // *** End programmer edit section *** (ТчЧертежи.Расширение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЧертежи.Расширение Set start)

                // *** End programmer edit section *** (ТчЧертежи.Расширение Set start)
                this.fРасширение = value;
                // *** Start programmer edit section *** (ТчЧертежи.Расширение Set end)

                // *** End programmer edit section *** (ТчЧертежи.Расширение Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya_novaya.Чертежи.
        /// </summary>
        // *** Start programmer edit section *** (ТчЧертежи.Чертежи CustomAttributes)

        // *** End programmer edit section *** (ТчЧертежи.Чертежи CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Чертежи"})]
        public virtual IIS.Generaciya_novaya.Чертежи Чертежи
        {
            get
            {
                // *** Start programmer edit section *** (ТчЧертежи.Чертежи Get start)

                // *** End programmer edit section *** (ТчЧертежи.Чертежи Get start)
                IIS.Generaciya_novaya.Чертежи result = this.fЧертежи;
                // *** Start programmer edit section *** (ТчЧертежи.Чертежи Get end)

                // *** End programmer edit section *** (ТчЧертежи.Чертежи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЧертежи.Чертежи Set start)

                // *** End programmer edit section *** (ТчЧертежи.Чертежи Set start)
                this.fЧертежи = value;
                // *** Start programmer edit section *** (ТчЧертежи.Чертежи Set end)

                // *** End programmer edit section *** (ТчЧертежи.Чертежи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчЧертежиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчЧертежиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчЧертежиE", typeof(IIS.Generaciya_novaya.ТчЧертежи));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчЧертежи.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчЧертежи CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчЧертежи CustomAttributes)
    public class DetailArrayOfТчЧертежи : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya_novaya.DetailArrayOfТчЧертежи members)

        // *** End programmer edit section *** (IIS.Generaciya_novaya.DetailArrayOfТчЧертежи members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчЧертежи by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчЧертежи.
        /// </summary>
        public DetailArrayOfТчЧертежи(IIS.Generaciya_novaya.Чертежи fЧертежи) : 
                base(typeof(ТчЧертежи), ((ICSSoft.STORMNET.DataObject)(fЧертежи)))
        {
        }
        
        public IIS.Generaciya_novaya.ТчЧертежи this[int index]
        {
            get
            {
                return ((IIS.Generaciya_novaya.ТчЧертежи)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya_novaya.ТчЧертежи dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
