//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_novaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч тех карты.
    /// </summary>
    // *** Start programmer edit section *** (ТЧТехКарты CustomAttributes)

    // *** End programmer edit section *** (ТЧТехКарты CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч тех карты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧТехКартыE", new string[] {
            "ПунктРаботы as \'Пункт работы\'",
            "СоставРабот as \'Состав работ\'",
            "Материалы as \'Материалы\'",
            "Материалы.Наименование as \'Необходимые материалы\'",
            "Оборудование as \'Оборудование\'",
            "Оборудование.Наименование as \'Необходимое оборудование\'"}, Hidden=new string[] {
            "Материалы.Наименование",
            "Оборудование.Наименование"})]
    [MasterViewDefineAttribute("ТЧТехКартыE", "Материалы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ТЧТехКартыE", "Оборудование", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ТЧТехКарты : ICSSoft.STORMNET.DataObject
    {
        
        private string fСоставРабот;
        
        private int fПунктРаботы;
        
        private IIS.Generaciya_novaya.Оборудование fОборудование;
        
        private IIS.Generaciya_novaya.Материалы fМатериалы;
        
        private IIS.Generaciya_novaya.ТехКарты fТехКарты;
        
        // *** Start programmer edit section *** (ТЧТехКарты CustomMembers)

        // *** End programmer edit section *** (ТЧТехКарты CustomMembers)

        
        /// <summary>
        /// ПунктРаботы.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТехКарты.ПунктРаботы CustomAttributes)

        // *** End programmer edit section *** (ТЧТехКарты.ПунктРаботы CustomAttributes)
        public virtual int ПунктРаботы
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТехКарты.ПунктРаботы Get start)

                // *** End programmer edit section *** (ТЧТехКарты.ПунктРаботы Get start)
                int result = this.fПунктРаботы;
                // *** Start programmer edit section *** (ТЧТехКарты.ПунктРаботы Get end)

                // *** End programmer edit section *** (ТЧТехКарты.ПунктРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТехКарты.ПунктРаботы Set start)

                // *** End programmer edit section *** (ТЧТехКарты.ПунктРаботы Set start)
                this.fПунктРаботы = value;
                // *** Start programmer edit section *** (ТЧТехКарты.ПунктРаботы Set end)

                // *** End programmer edit section *** (ТЧТехКарты.ПунктРаботы Set end)
            }
        }
        
        /// <summary>
        /// СоставРабот.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТехКарты.СоставРабот CustomAttributes)

        // *** End programmer edit section *** (ТЧТехКарты.СоставРабот CustomAttributes)
        [StrLen(255)]
        public virtual string СоставРабот
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТехКарты.СоставРабот Get start)

                // *** End programmer edit section *** (ТЧТехКарты.СоставРабот Get start)
                string result = this.fСоставРабот;
                // *** Start programmer edit section *** (ТЧТехКарты.СоставРабот Get end)

                // *** End programmer edit section *** (ТЧТехКарты.СоставРабот Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТехКарты.СоставРабот Set start)

                // *** End programmer edit section *** (ТЧТехКарты.СоставРабот Set start)
                this.fСоставРабот = value;
                // *** Start programmer edit section *** (ТЧТехКарты.СоставРабот Set end)

                // *** End programmer edit section *** (ТЧТехКарты.СоставРабот Set end)
            }
        }
        
        /// <summary>
        /// Т ч тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТехКарты.Материалы CustomAttributes)

        // *** End programmer edit section *** (ТЧТехКарты.Материалы CustomAttributes)
        [PropertyStorage(new string[] {
                "Материалы"})]
        [NotNull()]
        public virtual IIS.Generaciya_novaya.Материалы Материалы
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТехКарты.Материалы Get start)

                // *** End programmer edit section *** (ТЧТехКарты.Материалы Get start)
                IIS.Generaciya_novaya.Материалы result = this.fМатериалы;
                // *** Start programmer edit section *** (ТЧТехКарты.Материалы Get end)

                // *** End programmer edit section *** (ТЧТехКарты.Материалы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТехКарты.Материалы Set start)

                // *** End programmer edit section *** (ТЧТехКарты.Материалы Set start)
                this.fМатериалы = value;
                // *** Start programmer edit section *** (ТЧТехКарты.Материалы Set end)

                // *** End programmer edit section *** (ТЧТехКарты.Материалы Set end)
            }
        }
        
        /// <summary>
        /// Т ч тех карты.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТехКарты.Оборудование CustomAttributes)

        // *** End programmer edit section *** (ТЧТехКарты.Оборудование CustomAttributes)
        [PropertyStorage(new string[] {
                "Оборудование"})]
        [NotNull()]
        public virtual IIS.Generaciya_novaya.Оборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТехКарты.Оборудование Get start)

                // *** End programmer edit section *** (ТЧТехКарты.Оборудование Get start)
                IIS.Generaciya_novaya.Оборудование result = this.fОборудование;
                // *** Start programmer edit section *** (ТЧТехКарты.Оборудование Get end)

                // *** End programmer edit section *** (ТЧТехКарты.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТехКарты.Оборудование Set start)

                // *** End programmer edit section *** (ТЧТехКарты.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (ТЧТехКарты.Оборудование Set end)

                // *** End programmer edit section *** (ТЧТехКарты.Оборудование Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya_novaya.ТехКарты.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТехКарты.ТехКарты CustomAttributes)

        // *** End programmer edit section *** (ТЧТехКарты.ТехКарты CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ТехКарты"})]
        public virtual IIS.Generaciya_novaya.ТехКарты ТехКарты
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТехКарты.ТехКарты Get start)

                // *** End programmer edit section *** (ТЧТехКарты.ТехКарты Get start)
                IIS.Generaciya_novaya.ТехКарты result = this.fТехКарты;
                // *** Start programmer edit section *** (ТЧТехКарты.ТехКарты Get end)

                // *** End programmer edit section *** (ТЧТехКарты.ТехКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТехКарты.ТехКарты Set start)

                // *** End programmer edit section *** (ТЧТехКарты.ТехКарты Set start)
                this.fТехКарты = value;
                // *** Start programmer edit section *** (ТЧТехКарты.ТехКарты Set end)

                // *** End programmer edit section *** (ТЧТехКарты.ТехКарты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧТехКартыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧТехКартыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧТехКартыE", typeof(IIS.Generaciya_novaya.ТЧТехКарты));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧТехКарты.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧТехКарты CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧТехКарты CustomAttributes)
    public class DetailArrayOfТЧТехКарты : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya_novaya.DetailArrayOfТЧТехКарты members)

        // *** End programmer edit section *** (IIS.Generaciya_novaya.DetailArrayOfТЧТехКарты members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧТехКарты by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧТехКарты.
        /// </summary>
        public DetailArrayOfТЧТехКарты(IIS.Generaciya_novaya.ТехКарты fТехКарты) : 
                base(typeof(ТЧТехКарты), ((ICSSoft.STORMNET.DataObject)(fТехКарты)))
        {
        }
        
        public IIS.Generaciya_novaya.ТЧТехКарты this[int index]
        {
            get
            {
                return ((IIS.Generaciya_novaya.ТЧТехКарты)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya_novaya.ТЧТехКарты dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
