//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_novaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Чертежи.
    /// </summary>
    // *** Start programmer edit section *** (Чертежи CustomAttributes)

    // *** End programmer edit section *** (Чертежи CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧертежиE", new string[] {
            "НаименЧертеж as \'Наименование чертежа\'",
            "ДатаСоздания as \'Дата создания\'",
            "Заявки as \'Заявки\'",
            "Заявки.НомерЗаявки as \'Номер заявки\'"}, Hidden=new string[] {
            "Заявки.НомерЗаявки"})]
    [AssociatedDetailViewAttribute("ЧертежиE", "ТчЧертежи", "ТчЧертежиE", true, "", "Версии Чертежа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЧертежиE", "Заявки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЗаявки")]
    [View("ЧертежиL", new string[] {
            "НаименЧертеж as \'Наименование чертежа\'",
            "ДатаСоздания as \'Дата создания\'",
            "Заявки.НомерЗаявки as \'Номер заявки\'"})]
    public class Чертежи : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименЧертеж;
        
        private System.DateTime fДатаСоздания;
        
        private IIS.Generaciya_novaya.Заявки fЗаявки;
        
        private IIS.Generaciya_novaya.DetailArrayOfТчЧертежи fТчЧертежи;
        
        // *** Start programmer edit section *** (Чертежи CustomMembers)

        // *** End programmer edit section *** (Чертежи CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (Чертежи.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Get start)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Get end)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Set start)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (Чертежи.ДатаСоздания Set end)

                // *** End programmer edit section *** (Чертежи.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// НаименЧертеж.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.НаименЧертеж CustomAttributes)

        // *** End programmer edit section *** (Чертежи.НаименЧертеж CustomAttributes)
        [StrLen(255)]
        public virtual string НаименЧертеж
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.НаименЧертеж Get start)

                // *** End programmer edit section *** (Чертежи.НаименЧертеж Get start)
                string result = this.fНаименЧертеж;
                // *** Start programmer edit section *** (Чертежи.НаименЧертеж Get end)

                // *** End programmer edit section *** (Чертежи.НаименЧертеж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.НаименЧертеж Set start)

                // *** End programmer edit section *** (Чертежи.НаименЧертеж Set start)
                this.fНаименЧертеж = value;
                // *** Start programmer edit section *** (Чертежи.НаименЧертеж Set end)

                // *** End programmer edit section *** (Чертежи.НаименЧертеж Set end)
            }
        }
        
        /// <summary>
        /// Чертежи.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.Заявки CustomAttributes)

        // *** End programmer edit section *** (Чертежи.Заявки CustomAttributes)
        [PropertyStorage(new string[] {
                "Заявки"})]
        [NotNull()]
        public virtual IIS.Generaciya_novaya.Заявки Заявки
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.Заявки Get start)

                // *** End programmer edit section *** (Чертежи.Заявки Get start)
                IIS.Generaciya_novaya.Заявки result = this.fЗаявки;
                // *** Start programmer edit section *** (Чертежи.Заявки Get end)

                // *** End programmer edit section *** (Чертежи.Заявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.Заявки Set start)

                // *** End programmer edit section *** (Чертежи.Заявки Set start)
                this.fЗаявки = value;
                // *** Start programmer edit section *** (Чертежи.Заявки Set end)

                // *** End programmer edit section *** (Чертежи.Заявки Set end)
            }
        }
        
        /// <summary>
        /// Чертежи.
        /// </summary>
        // *** Start programmer edit section *** (Чертежи.ТчЧертежи CustomAttributes)

        // *** End programmer edit section *** (Чертежи.ТчЧертежи CustomAttributes)
        public virtual IIS.Generaciya_novaya.DetailArrayOfТчЧертежи ТчЧертежи
        {
            get
            {
                // *** Start programmer edit section *** (Чертежи.ТчЧертежи Get start)

                // *** End programmer edit section *** (Чертежи.ТчЧертежи Get start)
                if ((this.fТчЧертежи == null))
                {
                    this.fТчЧертежи = new IIS.Generaciya_novaya.DetailArrayOfТчЧертежи(this);
                }
                IIS.Generaciya_novaya.DetailArrayOfТчЧертежи result = this.fТчЧертежи;
                // *** Start programmer edit section *** (Чертежи.ТчЧертежи Get end)

                // *** End programmer edit section *** (Чертежи.ТчЧертежи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертежи.ТчЧертежи Set start)

                // *** End programmer edit section *** (Чертежи.ТчЧертежи Set start)
                this.fТчЧертежи = value;
                // *** Start programmer edit section *** (Чертежи.ТчЧертежи Set end)

                // *** End programmer edit section *** (Чертежи.ТчЧертежи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧертежиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧертежиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧертежиE", typeof(IIS.Generaciya_novaya.Чертежи));
                }
            }
            
            /// <summary>
            /// "ЧертежиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧертежиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧертежиL", typeof(IIS.Generaciya_novaya.Чертежи));
                }
            }
        }
    }
}
